version: '2'
services:
    jenkins:
        container_name: jenkins
        image: 4oh4/jenkins-docker
        restart: always
        volumes:
        - /var/jenkins_home:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
        ports:
        - "50000:50000"
        - "8090:8080"
